version: '3.9'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  api:
    build: ./api
    ports:
      - "5050:5050"
    volumes:
      - .:/code

  db:
    build: ./db
    ports:
      - "3306:3306"