version: '3.9'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: todo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080